apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name : auth
                  image: rampooco/sejutacita-auth
                  env :
                    - name : MONGO_URI
                      value : 'mongodb://users-mongo-clusterip:27017/users'
                    - name : JWT_KEY
                      valueFrom:
                        secretKeyRef:
                            name: sejutacita-jwt-secret
                            key : JWT_KEY
                    - name : JWT_REFRESH_KEY
                      valueFrom:
                        secretKeyRef:
                            name: sejutacita-jwt-secret
                            key : JWT_REFRESH_KEY
                    
---

apiVersion : v1
kind : Service
metadata : 
    name : auth-clusterip-service
spec: 
    selector:
        app: auth
    ports:
        - name : auth
          protocol : TCP
          port: 3000
          targetPort: 3000