apiVersion : networking.k8s.io/v1beta1
kind : Ingress
metadata : 
    name : ingress-srv
    annotations :
        kubernetes.io/ingress.class : nginx
        nginx.ingress.kubernetes.io/use-regex : 'true'
spec :
    rules :
        - host : sejutacita.dev
          http :
            paths :
                - path : /api/v1/users/?(.*)
                  backend :
                    serviceName : users-clusterip-service
                    servicePort : 3000
               